#!/usr/bin/env bash
# loop-ci generator — emit a GitHub Actions CI workflow to stdout from detected
# stack facts. A PURE function of its arguments (reads no files) so the golden
# tests can pin every branch. The /loop-ci command does the detecting (from
# .claude/loop/loop.config.md + the lockfile) and passes the facts here.
#
#   gen_ci.sh --pm <npm|pnpm|yarn|bun> [--test CMD] [--lint CMD] [--build CMD]
#
# An empty command, or one whose value starts with "TODO", is emitted as a
# commented-out step so the gap stays visible — never silently dropped.
set -u

PM=""
TEST=""
LINT=""
BUILD=""

while [ $# -gt 0 ]; do
  case "$1" in
    --pm)    PM="${2:-}";    shift 2 ;;
    --test)  TEST="${2:-}";  shift 2 ;;
    --lint)  LINT="${2:-}";  shift 2 ;;
    --build) BUILD="${2:-}"; shift 2 ;;
    -h|--help) sed -n 's/^# \{0,1\}//p' "$0" | sed '1d'; exit 0 ;;
    *) printf 'gen_ci.sh: unknown argument: %s\n' "$1" >&2; exit 2 ;;
  esac
done

case "$PM" in
  npm)  INSTALL="npm ci" ;;
  pnpm) INSTALL="pnpm install --frozen-lockfile" ;;
  yarn) INSTALL="yarn install --frozen-lockfile" ;;
  bun)  INSTALL="bun install --frozen-lockfile" ;;
  "")   printf 'gen_ci.sh: --pm is required (npm|pnpm|yarn|bun)\n' >&2; exit 2 ;;
  *)    printf 'gen_ci.sh: unsupported --pm: %s\n' "$PM" >&2; exit 2 ;;
esac

# emit a run step, or a commented TODO placeholder when the command is empty/TODO
emit_step() { # name, command
  case "$2" in
    ""|TODO*)
      printf '      # - name: %s\n      #   run: TODO — set %s in .claude/loop/loop.config.md\n' "$1" "$1"
      ;;
    *)
      printf '      - name: %s\n        run: %s\n' "$1" "$2"
      ;;
  esac
}

cat <<'YAML'
name: loop-ci

# Generated by loop-harness /loop-ci from .claude/loop/loop.config.md.
# Runs the same test/lint/build the loop verifies, so CI and the loop agree.
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
YAML

if [ "$PM" = "bun" ]; then
  printf '      - uses: oven-sh/setup-bun@v2\n'
else
  [ "$PM" = "pnpm" ] && printf '      - uses: pnpm/action-setup@v4\n'
  printf '      - uses: actions/setup-node@v4\n        with:\n          node-version: lts/*\n          cache: %s\n' "$PM"
fi

printf '      - name: install\n        run: %s\n' "$INSTALL"

emit_step lint "$LINT"
emit_step test "$TEST"
emit_step build "$BUILD"
